import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Smart pluralization to avoid naive 's' appending (e.g., Class → classes, not classs)
function pluralize(name) {
  const lower = name.toLowerCase();
  if (lower.endsWith('ss') || lower.endsWith('x') || lower.endsWith('ch') || lower.endsWith('sh')) return lower + 'es';
  if (lower.endsWith('s')) return lower + 'es';
  if (lower.endsWith('y') && !'aeiou'.includes(lower[lower.length - 2])) return lower.slice(0, -1) + 'ies';
  return lower + 's';
}

// ============================================
// TEMPLATES — Production-Ready Output
// ============================================

const tplPackageJson = (name) => JSON.stringify({
  name: `${name.toLowerCase()}-api`,
  version: '1.0.0',
  description: 'Generated by AutoMind — Next-Gen Backend Automation',
  main: 'server.js',
  type: 'module',
  scripts: { start: 'node server.js', dev: 'nodemon server.js' },
  dependencies: {
    bcryptjs: '^2.4.3', cors: '^2.8.5', dotenv: '^16.3.1',
    express: '^4.18.2', helmet: '^7.0.0', jsonwebtoken: '^9.0.2',
    mongoose: '^7.5.0', morgan: '^1.10.0',
  },
}, null, 2);

const tplEnv = () => `PORT=5000
MONGO_URI=mongodb://127.0.0.1:27017/automind-generated
JWT_SECRET=super_secret_automind_key_2026
`;

// --- Auth Middleware (JWT verify) ---
const tplAuthMiddleware = () => `import jwt from 'jsonwebtoken';

export const protect = (req, res, next) => {
  let token;
  if (req.headers.authorization?.startsWith('Bearer')) {
    try {
      token = req.headers.authorization.split(' ')[1];
      const decoded = jwt.verify(token, process.env.JWT_SECRET || 'automind_secret_123');
      req.user = decoded;
      next();
    } catch (err) {
      res.status(401).json({ message: 'Not authorized, token failed' });
    }
  } else {
    res.status(401).json({ message: 'Not authorized, no token provided' });
  }
};
`;

// --- Server entry point ---
const tplServer = (entityModels) => {
  // Build explicit route imports for entity models
  const routeImports = entityModels.map(
    (m) => `import ${m.name.toLowerCase()}Routes from './routes/${pluralize(m.name)}.js';`
  ).join('\n');

  const routeMounts = entityModels.map(
    (m) => `app.use('/api/${pluralize(m.name)}', ${m.name.toLowerCase()}Routes);`
  ).join('\n');

  return `import express from 'express';
import mongoose from 'mongoose';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import dotenv from 'dotenv';

import authRoutes from './routes/auth.js';
${routeImports}

dotenv.config();

const app = express();

app.use(helmet());
app.use(cors());
app.use(express.json());
app.use(morgan('dev'));

// --- Auth Routes (Register / Login) ---
app.use('/api/auth', authRoutes);

// --- Entity Routes (CRUD — all protected) ---
${routeMounts}

app.get('/', (req, res) => res.json({ status: 'ok', message: 'API is running — Generated by AutoMind' }));

const PORT = process.env.PORT || 5000;

mongoose.connect(process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/generated-db')
  .then(() => {
    console.log('✅ MongoDB Connected');
    app.listen(PORT, () => console.log(\`🚀 Server running on port \${PORT}\`));
  })
  .catch(err => console.error('❌ DB Connection Error:', err));
`;
};

// ============================================
// MODEL TEMPLATES
// ============================================

// Normalize fields: supports both array [{name,type,required}] and object {name:Type}
function normalizeFields(fields) {
  if (Array.isArray(fields)) return fields;
  return Object.entries(fields).map(([name, type]) => ({ name, type, required: true }));
}

// --- User Model (with bcrypt + matchPassword) ---
const tplUserModel = (model) => {
  const fieldList = normalizeFields(model.fields);
  const fields = fieldList.map((f) => {
    const extras = f.name === 'password' ? ', select: false' : f.name === 'email' ? ', unique: true' : '';
    return `  ${f.name}: { type: ${f.type}, required: ${f.required !== false}${extras} }`;
  }).join(',\n');

  return `import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';

const schema = new mongoose.Schema({
${fields}
}, { timestamps: true });

// Hash password before saving
schema.pre('save', async function(next) {
  if (!this.isModified('password')) return next();
  const salt = await bcrypt.genSalt(10);
  this.password = await bcrypt.hash(this.password, salt);
  next();
});

// Compare entered password with hashed password
schema.methods.matchPassword = async function(enteredPassword) {
  return await bcrypt.compare(enteredPassword, this.password);
};

export default mongoose.model('${model.name}', schema);
`;
};

// --- Entity Model (non-User — auto-injects user ownership ref) ---
const tplEntityModel = (model) => {
  const fieldList = normalizeFields(model.fields);

  // Filter out any 'user' field that might already exist (we inject our own)
  const filteredFields = fieldList.filter(f => f.name !== 'user');

  const fields = filteredFields.map((f) => {
    return `  ${f.name}: { type: ${f.type}, required: ${f.required !== false} }`;
  }).join(',\n');

  return `import mongoose from 'mongoose';

const schema = new mongoose.Schema({
${fields},
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true }
}, { timestamps: true });

export default mongoose.model('${model.name}', schema);
`;
};

// ============================================
// AUTH CONTROLLER (Register + Login)
// ============================================
const tplAuthController = () => `import jwt from 'jsonwebtoken';
import User from '../models/userModel.js';

// Generate JWT token
const generateToken = (user) => {
  return jwt.sign(
    { id: user._id, email: user.email, role: user.role || 'user' },
    process.env.JWT_SECRET || 'automind_secret_123',
    { expiresIn: '7d' }
  );
};

// @desc    Register a new user
// @route   POST /api/auth/register
// @access  Public
export const register = async (req, res) => {
  try {
    const { username, email, password, role } = req.body;

    // Check if user already exists
    const existingUser = await User.findOne({ email });
    if (existingUser) {
      return res.status(400).json({ message: 'User already exists with this email' });
    }

    // Create user (password is hashed by the pre-save hook)
    const user = await User.create({ username, email, password, role: role || 'user' });

    res.status(201).json({
      _id: user._id,
      username: user.username,
      email: user.email,
      role: user.role,
      token: generateToken(user),
    });
  } catch (error) {
    res.status(400).json({ message: error.message });
  }
};

// @desc    Login user & return JWT
// @route   POST /api/auth/login
// @access  Public
export const login = async (req, res) => {
  try {
    const { email, password } = req.body;

    if (!email || !password) {
      return res.status(400).json({ message: 'Please provide email and password' });
    }

    // Find user and explicitly select password (it is excluded by default)
    const user = await User.findOne({ email }).select('+password');

    if (!user) {
      return res.status(401).json({ message: 'Invalid email or password' });
    }

    // Verify password using the matchPassword instance method
    const isMatch = await user.matchPassword(password);
    if (!isMatch) {
      return res.status(401).json({ message: 'Invalid email or password' });
    }

    res.json({
      _id: user._id,
      username: user.username,
      email: user.email,
      role: user.role,
      token: generateToken(user),
    });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};
`;

// ============================================
// AUTH ROUTES (Register + Login)
// ============================================
const tplAuthRoutes = () => `import express from 'express';
import { register, login } from '../controllers/authController.js';

const router = express.Router();

// POST /api/auth/register
router.post('/register', register);

// POST /api/auth/login
router.post('/login', login);

export default router;
`;

// ============================================
// ENTITY ROUTES — Full CRUD, Scoped, Protected
// ============================================
const tplEntityRoutes = (name) => `import express from 'express';
import Model from '../models/${name.toLowerCase()}Model.js';
import { protect } from '../middleware/authMiddleware.js';

const router = express.Router();

// All routes are protected — user must be authenticated
// All queries are scoped to the authenticated user (req.user.id)

// @desc    Get all ${pluralize(name)} for the logged-in user
// @route   GET /api/${pluralize(name)}
// @access  Private
router.get('/', protect, async (req, res) => {
  try {
    const data = await Model.find({ user: req.user.id }).sort({ createdAt: -1 });
    res.json(data);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// @desc    Get a single ${name} by ID (only if owned by user)
// @route   GET /api/${pluralize(name)}/:id
// @access  Private
router.get('/:id', protect, async (req, res) => {
  try {
    const data = await Model.findOne({ _id: req.params.id, user: req.user.id });
    if (!data) return res.status(404).json({ message: '${name} not found' });
    res.json(data);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// @desc    Create a new ${name} (auto-assigned to logged-in user)
// @route   POST /api/${pluralize(name)}
// @access  Private
router.post('/', protect, async (req, res) => {
  try {
    const data = await Model.create({ ...req.body, user: req.user.id });
    res.status(201).json(data);
  } catch (error) {
    res.status(400).json({ message: error.message });
  }
});

// @desc    Update a ${name} by ID (only if owned by user)
// @route   PUT /api/${pluralize(name)}/:id
// @access  Private
router.put('/:id', protect, async (req, res) => {
  try {
    const data = await Model.findOneAndUpdate(
      { _id: req.params.id, user: req.user.id },
      req.body,
      { new: true, runValidators: true }
    );
    if (!data) return res.status(404).json({ message: '${name} not found or not authorized' });
    res.json(data);
  } catch (error) {
    res.status(400).json({ message: error.message });
  }
});

// @desc    Delete a ${name} by ID (only if owned by user)
// @route   DELETE /api/${pluralize(name)}/:id
// @access  Private
router.delete('/:id', protect, async (req, res) => {
  try {
    const data = await Model.findOneAndDelete({ _id: req.params.id, user: req.user.id });
    if (!data) return res.status(404).json({ message: '${name} not found or not authorized' });
    res.json({ message: '${name} deleted successfully' });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

export default router;
`;

// ============================================
// MAIN EXPORT: generateProject(schema)
// ============================================
export async function generateProject(schema) {
  const { projectName, models } = schema;
  const outDir = path.join(__dirname, `generated_${projectName.toLowerCase()}`);
  const generatedFiles = [];

  // Separate User model from entity models
  let userModel = models.find(m => m.name.toLowerCase() === 'user');
  const entityModels = models.filter(m => m.name.toLowerCase() !== 'user');

  // If no User model was provided, create a default one
  if (!userModel) {
    userModel = {
      name: 'User',
      fields: [
        { name: 'username', type: 'String', required: true },
        { name: 'email', type: 'String', required: true },
        { name: 'password', type: 'String', required: true },
        { name: 'role', type: 'String', required: false },
      ],
    };
  }

  // Create directory structure
  for (const sub of ['', 'models', 'routes', 'middleware', 'controllers']) {
    await fs.mkdir(path.join(outDir, sub), { recursive: true });
  }

  // --- Write root files ---
  const rootFiles = [
    ['package.json', tplPackageJson(projectName)],
    ['server.js', tplServer(entityModels)],
    ['.env', tplEnv()],
    [path.join('middleware', 'authMiddleware.js'), tplAuthMiddleware()],
    [path.join('controllers', 'authController.js'), tplAuthController()],
    [path.join('routes', 'auth.js'), tplAuthRoutes()],
  ];
  for (const [name, content] of rootFiles) {
    await fs.writeFile(path.join(outDir, name), content);
    generatedFiles.push(name);
  }

  // --- Write User model ---
  const userModelFile = 'models/userModel.js';
  await fs.writeFile(path.join(outDir, userModelFile), tplUserModel(userModel));
  generatedFiles.push(userModelFile);

  // --- Write entity models & routes (scoped to user) ---
  for (const model of entityModels) {
    const mFile = `models/${model.name.toLowerCase()}Model.js`;
    const rFile = `routes/${pluralize(model.name)}.js`;
    await fs.writeFile(path.join(outDir, mFile), tplEntityModel(model));
    await fs.writeFile(path.join(outDir, rFile), tplEntityRoutes(model.name));
    generatedFiles.push(mFile, rFile);
  }

  console.log(`✅ Generated ${generatedFiles.length} files in generated_${projectName.toLowerCase()}/`);
  return generatedFiles;
}
