import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// --- TEMPLATES ---

const tplPackageJson = (name) => JSON.stringify({
  name: `${name.toLowerCase()}-api`,
  version: '1.0.0',
  description: 'Generated by AutoMind',
  main: 'server.js',
  type: 'module',
  scripts: { start: 'node server.js', dev: 'nodemon server.js' },
  dependencies: {
    bcryptjs: '^2.4.3', cors: '^2.8.5', dotenv: '^16.3.1',
    express: '^4.18.2', helmet: '^7.0.0', jsonwebtoken: '^9.0.2',
    mongoose: '^7.5.0', morgan: '^1.10.0',
  },
}, null, 2);

const tplEnv = () => `PORT=5000
MONGO_URI=mongodb://127.0.0.1:27017/automind-generated
JWT_SECRET=super_secret_automind_key_2026
`;

const tplAuthMiddleware = () => `import jwt from 'jsonwebtoken';

export const protect = (req, res, next) => {
  let token;
  if (req.headers.authorization?.startsWith('Bearer')) {
    try {
      token = req.headers.authorization.split(' ')[1];
      req.user = jwt.verify(token, process.env.JWT_SECRET || 'automind_secret_123');
      next();
    } catch { res.status(401).json({ message: 'Token failed' }); }
  } else { res.status(401).json({ message: 'No token' }); }
};
`;

const tplServer = () => [
  "import express from 'express';",
  "import mongoose from 'mongoose';",
  "import cors from 'cors';",
  "import helmet from 'helmet';",
  "import morgan from 'morgan';",
  "import dotenv from 'dotenv';",
  "import fs from 'fs';",
  "import path from 'path';",
  "import { fileURLToPath } from 'url';",
  "",
  "dotenv.config();",
  "const app = express();",
  "app.use(helmet()); app.use(cors()); app.use(express.json()); app.use(morgan('dev'));",
  "",
  "const __filename = fileURLToPath(import.meta.url);",
  "const __dirname = path.dirname(__filename);",
  "const routesPath = path.join(__dirname, 'routes');",
  "",
  "if (fs.existsSync(routesPath)) {",
  "  for (const file of fs.readdirSync(routesPath).filter(f => f.endsWith('.js'))) {",
  "    const mod = await import(`./routes/${file}`);",
  "    app.use(`/api/${file.split('.')[0]}`, mod.default);",
  "  }",
  "}",
  "",
  "app.get('/', (req, res) => res.send('API running'));",
  "const PORT = process.env.PORT || 5000;",
  "mongoose.connect(process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/generated-db')",
  "  .then(() => { console.log('DB connected'); app.listen(PORT, () => console.log(`Port ${PORT}`)); })",
  "  .catch(err => console.error(err));",
].join('\n');

// Normalize fields: supports both array [{name,type,required}] and object {name:Type}
function normalizeFields(fields) {
  if (Array.isArray(fields)) return fields;
  return Object.entries(fields).map(([name, type]) => ({ name, type, required: true }));
}

const tplModel = (model) => {
  const fieldList = normalizeFields(model.fields);
  const fields = fieldList.map((f) => {
    const extras = f.name === 'password' ? ', select: false' : f.name === 'email' ? ', unique: true' : '';
    return `  ${f.name}: { type: ${f.type}, required: ${f.required !== false}${extras} }`;
  }).join(',\n');
  const hasPassword = fieldList.some(f => f.name === 'password');
  const lines = [
    "import mongoose from 'mongoose';",
    hasPassword ? "import bcrypt from 'bcryptjs';" : null,
    "",
    `const schema = new mongoose.Schema({\n${fields}\n}, { timestamps: true });`,
  ];
  if (hasPassword) {
    lines.push(
      "",
      "schema.pre('save', async function(next) {",
      "  if (!this.isModified('password')) return next();",
      "  this.password = await bcrypt.hash(this.password, 10);",
      "  next();",
      "});"
    );
  }
  lines.push("", `export default mongoose.model('${model.name}', schema);`);
  return lines.filter(l => l !== null).join('\n');
};

const tplRoute = (name) => [
  "import express from 'express';",
  `import Model from '../models/${name.toLowerCase()}Model.js';`,
  "import { protect } from '../middleware/authMiddleware.js';",
  "const router = express.Router();",
  "",
  "router.get('/', protect, async (req, res) => {",
  "  try { res.json(await Model.find()); }",
  "  catch (e) { res.status(500).json({ message: e.message }); }",
  "});",
  "",
  "router.get('/:id', protect, async (req, res) => {",
  "  try { const d = await Model.findById(req.params.id); d ? res.json(d) : res.status(404).json({ message: 'Not found' }); }",
  "  catch (e) { res.status(500).json({ message: e.message }); }",
  "});",
  "",
  "router.post('/', async (req, res) => {",
  "  try { res.status(201).json(await Model.create(req.body)); }",
  "  catch (e) { res.status(400).json({ message: e.message }); }",
  "});",
  "",
  "export default router;",
].join('\n');

// ============================================
// MAIN EXPORT: generateProject(schema)
// ============================================
export async function generateProject(schema) {
  const { projectName, models } = schema;
  const outDir = path.join(__dirname, `generated_${projectName.toLowerCase()}`);
  const generatedFiles = [];

  // Create dirs
  for (const sub of ['', 'models', 'routes', 'middleware']) {
    await fs.mkdir(path.join(outDir, sub), { recursive: true });
  }

  // Write root files
  const rootFiles = [
    ['package.json', tplPackageJson(projectName)],
    ['server.js', tplServer()],
    ['.env', tplEnv()],
    [path.join('middleware', 'authMiddleware.js'), tplAuthMiddleware()],
  ];
  for (const [name, content] of rootFiles) {
    await fs.writeFile(path.join(outDir, name), content);
    generatedFiles.push(name);
  }

  // Write models & routes
  for (const model of models) {
    const mFile = `models/${model.name.toLowerCase()}Model.js`;
    const rFile = `routes/${model.name.toLowerCase()}s.js`;
    await fs.writeFile(path.join(outDir, mFile), tplModel(model));
    await fs.writeFile(path.join(outDir, rFile), tplRoute(model.name));
    generatedFiles.push(mFile, rFile);
  }

  console.log(`✅ Generated ${generatedFiles.length} files in generated_${projectName.toLowerCase()}/`);
  return generatedFiles;
}
