import fs from 'fs/promises';
import path from 'path';

// --- TEMPLATES ---

const getPackageJson = (projectName) => `{
  "name": "${projectName.toLowerCase()}-api",
  "version": "1.0.0",
  "description": "Generated by AutoMind",
  "main": "server.js",
  "type": "module",
  "scripts": {
    "start": "node server.js",
    "dev": "nodemon server.js"
  },
  "dependencies": {
    "bcryptjs": "^2.4.3",
    "cors": "^2.8.5",
    "dotenv": "^16.3.1",
    "express": "^4.18.2",
    "helmet": "^7.0.0",
    "jsonwebtoken": "^9.0.2",
    "mongoose": "^7.5.0",
    "morgan": "^1.10.0"
  }
}`;

const getServerJs = () => `import express from 'express';
import mongoose from 'mongoose';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import dotenv from 'dotenv';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

dotenv.config();

const app = express();

app.use(helmet());
app.use(cors());
app.use(express.json());
app.use(morgan('dev'));

// Dynamically load routes
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const routesPath = path.join(__dirname, 'routes');

if (fs.existsSync(routesPath)) {
  const routeFiles = fs.readdirSync(routesPath).filter(file => file.endsWith('.js'));
  for (const file of routeFiles) {
    const routeModule = await import(\`./routes/\${file}\`);
    const routeName = file.split('.')[0];
    app.use(\`/api/\${routeName}\`, routeModule.default);
  }
}

app.get('/', (req, res) => res.send('API is running...'));

const PORT = process.env.PORT || 5000;

mongoose.connect(process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/generated-db')
  .then(() => {
    console.log('✅ MongoDB Connected');
    app.listen(PORT, () => console.log(\`🚀 Server running on port \${PORT}\`));
  })
  .catch(err => console.error('❌ DB Connection Error:', err));
`;

const getAuthMiddleware = () => `import jwt from 'jsonwebtoken';

export const protect = (req, res, next) => {
  let token;
  if (req.headers.authorization && req.headers.authorization.startsWith('Bearer')) {
    try {
      token = req.headers.authorization.split(' ')[1];
      const decoded = jwt.verify(token, process.env.JWT_SECRET || 'automind_secret_123');
      req.user = decoded;
      next();
    } catch (error) {
      res.status(401).json({ message: 'Not authorized, token failed' });
    }
  } else {
    res.status(401).json({ message: 'Not authorized, no token' });
  }
};
`;

const getModelJs = (model) => {
  let fields = '';
  for (const [key, val] of Object.entries(model.fields)) {
    if (key === 'password') {
      fields += `  ${key}: { type: ${val}, required: true, select: false },\n`;
    } else if (key === 'email') {
      fields += `  ${key}: { type: ${val}, required: true, unique: true },\n`;
    } else {
      fields += `  ${key}: { type: ${val}, required: true },\n`;
    }
  }

  return `import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';

const schema = new mongoose.Schema({
${fields}}, { timestamps: true });

// Hash password before saving
schema.pre('save', async function(next) {
  if (!this.isModified('password')) return next();
  const salt = await bcrypt.genSalt(10);
  this.password = await bcrypt.hash(this.password, salt);
  next();
});

// Compare password method
schema.methods.matchPassword = async function(enteredPassword) {
  return await bcrypt.compare(enteredPassword, this.password);
};

export default mongoose.model('${model.name}', schema);
`;
};

const getRouteJs = (modelName) => `import express from 'express';
import Model from '../models/${modelName.toLowerCase()}Model.js';
import { protect } from '../middleware/authMiddleware.js';

const router = express.Router();

// GET all
router.get('/', protect, async (req, res) => {
  try {
    const data = await Model.find();
    res.json(data);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// GET by ID
router.get('/:id', protect, async (req, res) => {
  try {
    const data = await Model.findById(req.params.id);
    if (!data) return res.status(404).json({ message: 'Not found' });
    res.json(data);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// POST new
router.post('/', async (req, res) => {
  try {
    const data = await Model.create(req.body);
    res.status(201).json(data);
  } catch (error) {
    res.status(400).json({ message: error.message });
  }
});

export default router;
`;

const getEnv = () => `PORT=5000
MONGO_URI=mongodb://127.0.0.1:27017/automind-generated
JWT_SECRET=super_secret_automind_key_2026
`;

// --- GENERATOR LOGIC ---

const runGenerator = async () => {
  try {
    console.log("🚀 Starting AutoMind Generator...");
    
    // Read Input JSON
    const rawData = await fs.readFile('./input.json', 'utf-8');
    const { projectName, models } = JSON.parse(rawData);
    
    const outputDir = path.join(process.cwd(), `generated_${projectName.toLowerCase()}`);
    
    // Create Folder Structure
    const dirs = [
      outputDir,
      path.join(outputDir, 'models'),
      path.join(outputDir, 'routes'),
      path.join(outputDir, 'middleware')
    ];
    
    for (const dir of dirs) {
      await fs.mkdir(dir, { recursive: true });
    }

    // Write Root Files
    await fs.writeFile(path.join(outputDir, 'package.json'), getPackageJson(projectName));
    await fs.writeFile(path.join(outputDir, 'server.js'), getServerJs());
    await fs.writeFile(path.join(outputDir, '.env'), getEnv());
    await fs.writeFile(path.join(outputDir, 'middleware', 'authMiddleware.js'), getAuthMiddleware());

    // Write Models and Routes
    if (models && models.length > 0) {
      for (const model of models) {
        const modelName = model.name.toLowerCase();
        await fs.writeFile(path.join(outputDir, 'models', `${modelName}Model.js`), getModelJs(model));
        await fs.writeFile(path.join(outputDir, 'routes', `${modelName}s.js`), getRouteJs(model.name));
      }
    }

    console.log(`✅ API generated successfully in folder: generated_${projectName.toLowerCase()}`);
    console.log("👉 Next steps: cd into folder, run 'npm install', then 'npm start'");

  } catch (error) {
    console.error("❌ Generator failed:", error.message);
  }
};

runGenerator();
