// Robust Engine ported from legacy backend/generatorEngine.js

export function pluralizeName(name: string) {
  const lower = name.toLowerCase();
  if (lower.endsWith('ss') || lower.endsWith('x') || lower.endsWith('ch') || lower.endsWith('sh')) return lower + 'es';
  if (lower.endsWith('s')) return lower + 'es';
  if (lower.endsWith('y') && !'aeiou'.includes(lower[lower.length - 2])) return lower.slice(0, -1) + 'ies';
  return lower + 's';
}

function normalizeFields(fields: any) {
  if (Array.isArray(fields)) return fields;
  return Object.entries(fields).map(([name, type]) => ({ name, type, required: true }));
}

// ============================================
// TEMPLATES
// ============================================

const getPackageJson = (projectName: string) => JSON.stringify({
  name: `${projectName.toLowerCase()}-api`,
  version: '1.0.0',
  type: 'module',
  scripts: { start: 'node server.js' },
  dependencies: {
    bcryptjs: '^2.4.3',
    cors: '^2.8.5',
    dotenv: '^16.3.1',
    express: '^4.18.2',
    helmet: '^7.0.0',
    jsonwebtoken: '^9.0.2',
    mongoose: '^7.5.0',
    morgan: '^1.10.0'
  }
}, null, 2);

const getServerJs = (projectName: string, entityModels: any[]) => {
  const routeImports = entityModels.map(
    (m) => `import ${m.name.toLowerCase()}Routes from './routes/${pluralizeName(m.name)}.js';`
  ).join('\n');

  const routeMounts = entityModels.map(
    (m) => `app.use('/api/${pluralizeName(m.name)}', ${m.name.toLowerCase()}Routes);`
  ).join('\n');

  return `import express from 'express';
import mongoose from 'mongoose';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import dotenv from 'dotenv';

import authRoutes from './routes/auth.js';
${routeImports}

dotenv.config();

const app = express();

app.use(helmet());
app.use(cors());
app.use(express.json());
app.use(morgan('dev'));

// Auth Routes
app.use('/api/auth', authRoutes);

// Entity Routes
${routeMounts}

app.get('/', (req, res) => res.json({ status: 'ok', message: 'API generated by AutoMind' }));

const PORT = process.env.PORT || 5000;
const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/${projectName.toLowerCase()}';

mongoose.connect(MONGO_URI)
  .then(() => {
    console.log('✅ MongoDB Connected');
    app.listen(PORT, () => console.log(\`🚀 Server running on port \${PORT}\`));
  })
  .catch(err => console.error('❌ DB Connection Error:', err));
`;
};

const getAuthMiddleware = () => `import jwt from 'jsonwebtoken';

export const protect = (req, res, next) => {
  let token;
  if (req.headers.authorization?.startsWith('Bearer')) {
    try {
      token = req.headers.authorization.split(' ')[1];
      const decoded = jwt.verify(token, process.env.JWT_SECRET || 'automind_secret_123');
      req.user = decoded;
      next();
    } catch (err) {
      res.status(401).json({ message: 'Not authorized, token failed' });
    }
  } else {
    res.status(401).json({ message: 'Not authorized, no token provided' });
  }
};
`;

const getAuthController = () => `import jwt from 'jsonwebtoken';
import User from '../models/userModel.js';

const generateToken = (user) => {
  return jwt.sign(
    { id: user._id, email: user.email, role: user.role || 'user' },
    process.env.JWT_SECRET || 'automind_secret_123',
    { expiresIn: '7d' }
  );
};

export const register = async (req, res) => {
  try {
    const { username, email, password, role } = req.body;
    const existingUser = await User.findOne({ email });
    if (existingUser) return res.status(400).json({ message: 'User already exists' });
    const user = await User.create({ username, email, password, role: role || 'user' });
    res.status(201).json({ _id: user._id, username: user.username, email: user.email, token: generateToken(user) });
  } catch (err) { res.status(400).json({ message: err.message }); }
};

export const login = async (req, res) => {
  try {
    const { email, password } = req.body;
    const user = await User.findOne({ email }).select('+password');
    if (!user || !(await user.matchPassword(password))) {
      return res.status(401).json({ message: 'Invalid email or password' });
    }
    res.json({ _id: user._id, username: user.username, email: user.email, token: generateToken(user) });
  } catch (err) { res.status(500).json({ message: err.message }); }
};
`;

const getEntityModel = (model: any) => {
  const fieldList = normalizeFields(model.fields);
  const fields = fieldList.map((f: any) => `  ${f.name}: { type: ${f.type}, required: ${f.required !== false} }`).join(',\n');
  return `import mongoose from 'mongoose';

const schema = new mongoose.Schema({
${fields},
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true }
}, { timestamps: true });

export default mongoose.model('${model.name}', schema);
`;
};

const getEntityRoutes = (modelName: string) => `import express from 'express';
import Model from '../models/${modelName.toLowerCase()}Model.js';
import { protect } from '../middleware/authMiddleware.js';

const router = express.Router();

router.get('/', protect, async (req, res) => {
  try {
    const data = await Model.find({ user: req.user.id }).sort({ createdAt: -1 });
    res.json(data);
  } catch (err) { res.status(500).json({ message: err.message }); }
});

router.post('/', protect, async (req, res) => {
  try {
    const data = await Model.create({ ...req.body, user: req.user.id });
    res.status(201).json(data);
  } catch (err) { res.status(400).json({ message: err.message }); }
});

router.get('/:id', protect, async (req, res) => {
  try {
    const data = await Model.findOne({ _id: req.params.id, user: req.user.id });
    if (!data) return res.status(404).json({ message: 'Not found' });
    res.json(data);
  } catch (err) { res.status(500).json({ message: err.message }); }
});

router.put('/:id', protect, async (req, res) => {
  try {
    const data = await Model.findOneAndUpdate({ _id: req.params.id, user: req.user.id }, req.body, { new: true });
    if (!data) return res.status(404).json({ message: 'Not found' });
    res.json(data);
  } catch (err) { res.status(400).json({ message: err.message }); }
});

router.delete('/:id', protect, async (req, res) => {
  try {
    const data = await Model.findOneAndDelete({ _id: req.params.id, user: req.user.id });
    if (!data) return res.status(404).json({ message: 'Not found' });
    res.json({ message: 'Deleted successfully' });
  } catch (err) { res.status(500).json({ message: err.message }); }
});

export default router;
`;

export async function generateProject(schema: any) {
  const { projectName, models } = schema;
  const files: Record<string, string> = {};

  let userModel = models.find((m: any) => m.name.toLowerCase() === 'user');
  const entityModels = models.filter((m: any) => m.name.toLowerCase() !== 'user');

  if (!userModel) {
    userModel = {
      name: 'User',
      fields: [
        { name: 'username', type: 'String', required: true },
        { name: 'email', type: 'String', required: true },
        { name: 'password', type: 'String', required: true },
        { name: 'role', type: 'String', required: false },
      ],
    };
  }

  files['package.json'] = getPackageJson(projectName);
  files['server.js'] = getServerJs(projectName, entityModels);
  files['.env'] = `PORT=5000\nMONGO_URI=mongodb://localhost:27017/${projectName.toLowerCase()}\nJWT_SECRET=automind_secret_${Math.random().toString(36).substring(7)}\n`;
  files['middleware/authMiddleware.js'] = getAuthMiddleware();
  files['controllers/authController.js'] = getAuthController();
  files['routes/auth.js'] = `import express from 'express';\nimport { register, login } from '../controllers/authController.js';\nconst router = express.Router();\nrouter.post('/register', register);\nrouter.post('/login', login);\nexport default router;\n`;
  
  // User Model
  files['models/userModel.js'] = `import mongoose from 'mongoose';\nimport bcrypt from 'bcryptjs';\n\nconst schema = new mongoose.Schema({\n${normalizeFields(userModel.fields).map((f: any) => `  ${f.name}: { type: ${f.type}, required: true${f.name === 'email' ? ', unique: true' : ''}${f.name === 'password' ? ', select: false' : ''} }`).join(',\\n')}\n}, { timestamps: true });\n\nschema.pre('save', async function(next) {\n  if (!this.isModified('password')) return next();\n  this.password = await bcrypt.hash(this.password, 10);\n  next();\n});\n\nschema.methods.matchPassword = async function(enteredPassword) {\n  return await bcrypt.compare(enteredPassword, this.password);\n};\n\nexport default mongoose.model('User', schema);\n`;

  // Entity Models & Routes
  for (const model of entityModels) {
    files[`models/${model.name.toLowerCase()}Model.js`] = getEntityModel(model);
    files[`routes/${pluralizeName(model.name)}.js`] = getEntityRoutes(model.name);
  }

  return files;
}

