// ============================================
// Vercel Serverless Function — /api/build
// ============================================

// Smart pluralization
function pluralize(name) {
  const lower = name.toLowerCase();
  if (lower.endsWith('ss') || lower.endsWith('x') || lower.endsWith('ch') || lower.endsWith('sh')) return lower + 'es';
  if (lower.endsWith('s')) return lower + 'es';
  if (lower.endsWith('y') && !'aeiou'.includes(lower[lower.length - 2])) return lower.slice(0, -1) + 'ies';
  return lower + 's';
}

// Normalize fields
function normalizeFields(fields) {
  if (Array.isArray(fields)) return fields;
  return Object.entries(fields).map(([name, type]) => ({ name, type, required: true }));
}

// ============================================
// TEMPLATES
// ============================================

const tplPackageJson = (name) => JSON.stringify({
  name: `${name.toLowerCase()}-api`,
  version: '1.0.0',
  description: 'Generated by AutoMind — Next-Gen Backend Automation',
  main: 'server.js',
  type: 'module',
  scripts: { start: 'node server.js', dev: 'nodemon server.js' },
  dependencies: {
    bcryptjs: '^2.4.3', cors: '^2.8.5', dotenv: '^16.3.1',
    express: '^4.18.2', helmet: '^7.0.0', jsonwebtoken: '^9.0.2',
    mongoose: '^7.5.0', morgan: '^1.10.0',
  },
}, null, 2);

const tplEnv = () => `PORT=5000
MONGO_URI=mongodb://127.0.0.1:27017/automind-generated
JWT_SECRET=super_secret_automind_key_2026
`;

const tplGitignore = () => `.env
.env.local
.env.production
node_modules/
*.log
.DS_Store
`;

const tplAuthMiddleware = () => `import jwt from 'jsonwebtoken';

export const protect = (req, res, next) => {
  let token;
  if (req.headers.authorization?.startsWith('Bearer')) {
    try {
      token = req.headers.authorization.split(' ')[1];
      const decoded = jwt.verify(token, process.env.JWT_SECRET || 'automind_secret_123');
      req.user = decoded;
      next();
    } catch (err) {
      res.status(401).json({ message: 'Not authorized, token failed' });
    }
  } else {
    res.status(401).json({ message: 'Not authorized, no token provided' });
  }
};
`;

const tplServer = (entityModels) => {
  const routeImports = entityModels.map(
    (m) => `import ${m.name.toLowerCase()}Routes from './routes/${pluralize(m.name)}.js';`
  ).join('\n');
  const routeMounts = entityModels.map(
    (m) => `app.use('/api/${pluralize(m.name)}', ${m.name.toLowerCase()}Routes);`
  ).join('\n');

  return `import express from 'express';
import mongoose from 'mongoose';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import dotenv from 'dotenv';

import authRoutes from './routes/auth.js';
${routeImports}

dotenv.config();

const app = express();

app.use(helmet());
app.use(cors());
app.use(express.json());
app.use(morgan('dev'));

app.use('/api/auth', authRoutes);
${routeMounts}

app.get('/', (req, res) => res.json({ status: 'ok', message: 'API is running — Generated by AutoMind' }));

const PORT = process.env.PORT || 5000;

mongoose.connect(process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/generated-db')
  .then(() => {
    console.log('✅ MongoDB Connected');
    app.listen(PORT, () => console.log(\`🚀 Server running on port \${PORT}\`));
  })
  .catch(err => console.error('❌ DB Connection Error:', err));
`;
};

const tplUserModel = (model) => {
  const fieldList = normalizeFields(model.fields);
  const fields = fieldList.map((f) => {
    const extras = f.name === 'password' ? ', select: false' : f.name === 'email' ? ', unique: true' : '';
    return `  ${f.name}: { type: ${f.type}, required: ${f.required !== false}${extras} }`;
  }).join(',\n');

  return `import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';

const schema = new mongoose.Schema({
${fields}
}, { timestamps: true });

schema.pre('save', async function(next) {
  if (!this.isModified('password')) return next();
  const salt = await bcrypt.genSalt(10);
  this.password = await bcrypt.hash(this.password, salt);
  next();
});

schema.methods.matchPassword = async function(enteredPassword) {
  return await bcrypt.compare(enteredPassword, this.password);
};

export default mongoose.model('${model.name}', schema);
`;
};

const tplEntityModel = (model) => {
  const fieldList = normalizeFields(model.fields);
  const filteredFields = fieldList.filter(f => f.name !== 'user');
  const fields = filteredFields.map((f) => {
    return `  ${f.name}: { type: ${f.type}, required: ${f.required !== false} }`;
  }).join(',\n');

  return `import mongoose from 'mongoose';

const schema = new mongoose.Schema({
${fields},
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true }
}, { timestamps: true });

export default mongoose.model('${model.name}', schema);
`;
};

const tplAuthController = () => `import jwt from 'jsonwebtoken';
import User from '../models/userModel.js';

const generateToken = (user) => {
  return jwt.sign(
    { id: user._id, email: user.email, role: user.role || 'user' },
    process.env.JWT_SECRET || 'automind_secret_123',
    { expiresIn: '7d' }
  );
};

export const register = async (req, res) => {
  try {
    const { username, email, password, role } = req.body;
    const existingUser = await User.findOne({ email });
    if (existingUser) return res.status(400).json({ message: 'User already exists with this email' });
    const user = await User.create({ username, email, password, role: role || 'user' });
    res.status(201).json({ _id: user._id, username: user.username, email: user.email, role: user.role, token: generateToken(user) });
  } catch (error) { res.status(400).json({ message: error.message }); }
};

export const login = async (req, res) => {
  try {
    const { email, password } = req.body;
    if (!email || !password) return res.status(400).json({ message: 'Please provide email and password' });
    const user = await User.findOne({ email }).select('+password');
    if (!user) return res.status(401).json({ message: 'Invalid email or password' });
    const isMatch = await user.matchPassword(password);
    if (!isMatch) return res.status(401).json({ message: 'Invalid email or password' });
    res.json({ _id: user._id, username: user.username, email: user.email, role: user.role, token: generateToken(user) });
  } catch (error) { res.status(500).json({ message: error.message }); }
};
`;

const tplAuthRoutes = () => `import express from 'express';
import { register, login } from '../controllers/authController.js';

const router = express.Router();

router.post('/register', register);
router.post('/login', login);

export default router;
`;

const tplEntityRoutes = (name) => `import express from 'express';
import Model from '../models/${name.toLowerCase()}Model.js';
import { protect } from '../middleware/authMiddleware.js';

const router = express.Router();

router.get('/', protect, async (req, res) => {
  try { const data = await Model.find({ user: req.user.id }).sort({ createdAt: -1 }); res.json(data); }
  catch (error) { res.status(500).json({ message: error.message }); }
});

router.get('/:id', protect, async (req, res) => {
  try { const data = await Model.findOne({ _id: req.params.id, user: req.user.id }); if (!data) return res.status(404).json({ message: '${name} not found' }); res.json(data); }
  catch (error) { res.status(500).json({ message: error.message }); }
});

router.post('/', protect, async (req, res) => {
  try { const data = await Model.create({ ...req.body, user: req.user.id }); res.status(201).json(data); }
  catch (error) { res.status(400).json({ message: error.message }); }
});

router.put('/:id', protect, async (req, res) => {
  try { const data = await Model.findOneAndUpdate({ _id: req.params.id, user: req.user.id }, req.body, { new: true, runValidators: true }); if (!data) return res.status(404).json({ message: '${name} not found or not authorized' }); res.json(data); }
  catch (error) { res.status(400).json({ message: error.message }); }
});

router.delete('/:id', protect, async (req, res) => {
  try { const data = await Model.findOneAndDelete({ _id: req.params.id, user: req.user.id }); if (!data) return res.status(404).json({ message: '${name} not found or not authorized' }); res.json({ message: '${name} deleted successfully' }); }
  catch (error) { res.status(500).json({ message: error.message }); }
});

export default router;
`;

// ============================================
// MAIN HANDLER
// ============================================
export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ message: 'Method not allowed' });

  const { schema } = req.body;
  if (!schema || !schema.projectName) return res.status(400).json({ message: 'Valid schema is required' });

  try {
    const { projectName, models } = schema;
    const generatedFiles = {};

    let userModel = models.find(m => m.name.toLowerCase() === 'user');
    const entityModels = models.filter(m => m.name.toLowerCase() !== 'user');

    if (!userModel) {
      userModel = {
        name: 'User',
        fields: [
          { name: 'username', type: 'String', required: true },
          { name: 'email', type: 'String', required: true },
          { name: 'password', type: 'String', required: true },
          { name: 'role', type: 'String', required: false },
        ],
      };
    }

    // Generate all files in memory (no filesystem in serverless)
    generatedFiles['package.json'] = tplPackageJson(projectName);
    generatedFiles['server.js'] = tplServer(entityModels);
    generatedFiles['.env'] = tplEnv();
    generatedFiles['.gitignore'] = tplGitignore();
    generatedFiles['middleware/authMiddleware.js'] = tplAuthMiddleware();
    generatedFiles['controllers/authController.js'] = tplAuthController();
    generatedFiles['routes/auth.js'] = tplAuthRoutes();
    generatedFiles['models/userModel.js'] = tplUserModel(userModel);

    for (const model of entityModels) {
      generatedFiles[`models/${model.name.toLowerCase()}Model.js`] = tplEntityModel(model);
      generatedFiles[`routes/${pluralize(model.name)}.js`] = tplEntityRoutes(model.name);
    }

    return res.json({
      files: Object.keys(generatedFiles),
      fileContents: generatedFiles,
      projectName,
      message: 'API generated successfully!',
    });
  } catch (err) {
    console.error('Build error:', err.message);
    return res.status(500).json({ message: 'Build failed: ' + err.message });
  }
}
